### ISSUE TITLE
Display shareholders of company(react)

### ISSUE THREAD

**Issue by kc-si** [kc-si/JSCLook#18]
Shareholders should be shown as bootstrapped table.

**Comment by marekciupak** [comment]
> Further database should store historical data of shareholders, so user can look at shareholders changing in timeline.

Is storing historical data a part of this task?

**Comment by kc-si** [comment]
> Is storing historical data a part of this task or just the context and notes for the future?
It is not part of this task, it is just the context and notes for the future.

Yes that is overlapping with this one [#68](https://github.com/kc-si/JSCLook/issues/68).
Updated.
