### ISSUE TITLE
Setup production

### ISSUE THREAD

**Issue by marekciupak** [kc-si/JSCLook#7]
The goal is to have this application running online, so anyone can open it as any other website on the Internet.

The guide: https://devcenter.heroku.com/articles/getting-started-with-rails7.

Note:
The guide tells you to use `heroku create` command. That command accepts the name of the project, for example:
```shell
heroku create jsclook
```
Try to use it with your project name and you will get a nicer URL instead of a random one.

**Comment by kc-si** [comment]
Production setuped, heroke Url:
https://jsclook.herokuapp.com/

**Comment by kc-si** [comment]
Production setuped, heroke Url:
https://jsclook.herokuapp.com/
